default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: nline
  password: n.Line2020
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: picbox_development

test:
  <<: *default
  database: picbox_test

production:
  <<: *default
  database: picbox_production
  username: nline
  password: n.Line2020
